version: '2'

services:
  base:
    build: .
    container_name: arrecadar-base
    volumes:
      - ./:/api
      - /api/node_modules

  yarn:
    extends: base
    entrypoint: /usr/local/bin/yarn

  mongo:
    image: mongo:3.6.3
    command: mongod --nojournal
    container_name: arrecadar-mongo
    expose:
      - 27017

  api-base:
    extends: base
    container_name: arrecadar-api-base

  api-live:
    extends: api-base
    command: yarn start
    container_name: arrecadar-api-live
    ports:
      - 80:3000
    links:
      - mongo

  api-dev:
    extends: api-base
    command: yarn dev
    container_name: arrecadar-api-dev
    env_file: .env
    ports:
      - 3000:3000
    links:
      - mongo
